/* global require */
require.config({
    baseUrl: '/etc/clientlibs/kpmgpublic',
    waitSeconds: 120,
    shim: {
        // Make Handlesbars available
        'handlebars': {
            exports: 'Handlebars'
        },
        'lazyload': {
            deps: ['jquery'],
            exports: 'lazyload'
        },
        'renditionimage': {
            deps: ['jquery'],
            exports: 'renditionimage'
        },
        'jquery.sidr': {
            exports: 'sidr'
        },
        'jquery.sly': {
            deps: ['jquery'],
            exports: '$.fn.sly'
        },
        'bootstrap': {
            deps: ['jquery']
        },
        'typeahead': {
            deps: ['jquery'],
            exports: '$.fn.typeahead'
        },
        'jquerysharebtn': {
            deps: ['jquery']
        },
        'jsonviewer': {
            deps: ['jquery', 'jqueryui'],
            exports: '$.fn.jsonViewer'
        },
        'jquerytap': {
            deps: ['jquery'],
            exports: 'jquerytap'
        },
        'modernizr': {
            exports: 'Modernizr'
        },
        'clamp': {
            deps: ['jquery'],
            exports: '$clamp'
        },
        'cookiemgr': {
            deps: ['jquery'],
            exports: 'cookiemgr'
        },
        'privacy': {
            deps: ['jquery'],
            exports: 'privacy'
        },
        'jqueryh5validate': {
            deps: ['jquery']
        },
        'customScrollbar': {
            deps: ['jquery', 'mousewheel'],
            exports: 'customScrollbar'
        },
        'responsiveTabs': {
            deps: ['jquery']
        },
        'tooltip': {
            deps: ['jquery']
        }
    },
    paths: {
        // Libraries
        'moment': 'global/js/vendor/moment',
        'jquery': 'global/js/vendor/jquery/jquery-3.3.1.min',
        'jquerysly': 'global/js/vendor/plugins/sly.min',
        'jquerysidr': 'global/js/vendor/plugins/jquery.sidr.min',
        'jqueryeasing': 'global/js/vendor/jquery/jquery.easing.min',
        'jqueryui': 'global/js/vendor/jquery/jquery.ui.min',
        'jquerytap': 'global/js/vendor/jquery/jquery.tap.min',
        'jquerymobilereflow': 'global/js/vendor/jquery/jquery.mobileReflow',
        //adding jquerymockajax plugin for rapid development
        'jquerymockajax': 'global/js/vendor/jquery/jquery.mockjax.min',
        'modernizr': 'global/js/vendor/modernizr.min',
        'handlebars': 'global/js/vendor/handlebars.min',
        'handlebars.runtime': 'global/js/vendor/handlebars.runtime.amd.min',
        'precompile': 'global/js/precompile',
        'respond': 'global/js/vendor/respond.min',
        'owl': 'global/js/vendor/plugins/owl.carousel.min',
        'text': 'global/js/vendor/text.min',
        'bootstrap': 'global/js/vendor/bootstrap.min',
        //
        'vue': 'global/js/vendor/vue.min',
        'vuex': 'global/js/vendor/vuex',
        'bootstrap4': 'global/js/vendor/bootstrap4',
        //
        'responsiveTabs': 'global/js/vendor/plugins/responsiveTabs.min',
        'brightcoveExperiences': 'global/js/vendor/plugins/brightcoveexperiences.min',
        'typeahead': 'global/js/vendor/plugins/typeahead.min',
        'placeholder': 'global/js/vendor/plugins/placeholders.min',
        'clamp': 'global/js/vendor/clamp.min',
        'lazyload': 'global/js/vendor/plugins/jquery.kpmg-unveil.min',
        'detectresize': 'global/js/vendor/plugins/jquery.detectresize.min',
        'cqservice': 'global/js/vendor/ajax-manager',
        'router': 'global/js/vendor/router',
        'gigya': 'global/js/vendor/plugins/gigya',
        'jsonviewer': 'global/js/vendor/plugins/jquery.json-viewer',
        'handlebarshelpers': 'global/js/vendor/handlebars-helpers',
        'helpers': 'global/js/vendor/helpers',
        'tracking': 'global/js/vendor/tracking',
        'jqueryh5validate': 'global/js/vendor/jquery.h5validate',
        'jquerysharebtn': 'global/js/vendor/jquery/jquery.sharebutton',
        'cookiemgr': 'global/js/vendor/jquery/jquery.cookie',
        'underscore': 'global/js/vendor/plugins/underscore-min',
        'privacy': 'global/js/vendor/privacy',
        'renditionimage': 'global/js/vendor/renditionimage',
        'customScrollbar': 'global/js/vendor/plugins/jquery.mCustomScrollbar.min',
        'mousewheel': 'global/js/vendor/jquery/jquery.mousewheel',
        'tooltip': 'global/js/vendor/tooltip',
        'personalization': 'global/js/personalization',
        'personalizationUtils': 'global/js/personalizationUtils',
        'resendVerificationEmail': 'global/js/resendVerificationEmail',
        'genericErrorDialog': 'global/js/genericErrorDialog',
        'autoscroll': 'global/js/autoScroll',

        // Modules
        'share': 'share/js/share',
        'event': 'event/js/event',
        'anchorlinks': 'anchorlinks/js/anchorlinks',
        'socialchannels': 'socialchannels/js/socialchannels',
        'herocarousel': 'herocarousel/js/herocarousel',
        'navigation': 'navigation/js/navigation',
        'footer': 'footer/js/footer',
        'breadcrumb': 'breadcrumb/js/breadcrumb',
        'bodytext': 'bodytext/js/bodytext',
        'connectandrfp': 'connectandrfp/js/connectandrfp',
        'connectwithme': 'connectwithme/js/connectwithme',
        'filmstripcarousel': 'filmstripcarousel/js/filmstripcarousel',
        'carouselview': 'carouselview/js/carouselview',
        'downloadbutton': 'downloadbutton/js/downloadbutton',
        'inlinelist': 'inlinelist/js/inlinelist',
        'subheading': 'subheading/js/subheading',
        'eventspeakers': 'eventspeakers/js/eventspeakers',
        'image': 'image/js/image',
        'leftalignedimagecarousel': 'leftalignedimagecarousel/js/leftalignedimagecarousel',
        'pagetitlevariant1': 'pagetitlevariant1/js/pagetitlevariant1',
        'pagetitlevariant2': 'pagetitlevariant2/js/pagetitlevariant2',
        'contentslider': 'contentslider/js/contentslider',
        'shortcarousel': 'shortcarousel/js/shortcarousel',
        'subnavigation': 'subnavigation/js/subnavigation',
        'contactcredentials': 'contactcredentials/js/contactcredentials',
        'pagetitle': 'pagetitle/js/pagetitle',
        'basicpagetitle': 'basicpagetitle/js/basicpagetitle',
        'tagcloud': 'tagcloud/js/tagcloud',
        'promovariantd': 'promovariantd/js/promovariantd',
        'trendinglist': 'trendinglist/js/trendinglist',
        'googlemap': 'googlemap/js/googlemap',
        'socialwidget': 'socialwidget/js/socialwidget',
        'authors': 'authors/js/authors',
        'htmlcontainer': 'htmlcontainer/js/htmlcontainer',
        'articleintroduction': 'articleintroduction/js/articleintroduction',
        'featuredtopics': 'featuredtopics/js/featuredtopics',
        'contactcarousel': 'contactcarousel/js/contactcarousel',
        'featuredarticles': 'featuredarticles/js/featuredarticles',
        'publicationserieslist': 'publicationserieslist/js/publicationserieslist',
        'peoplefilmstrip': 'peoplefilmstrip/js/peoplefilmstrip',
        'contactdetail': 'contactdetail/js/contactdetail',
        'navflyout': 'navflyout/js/navflyouta',
        'copyrightlist': 'copyrightlist/js/copyrightlist',
        'navflyouta': 'navflyouta/js/navflyouta',
        'ammaps': 'ammaps/js/ammaps',
        'amcharts': 'amcharts/js/amcharts',
        'relatedcontent': 'relatedcontent/js/relatedcontent',
        'newstool': 'newstool/js/newstool',
        'modallink': 'modallink/js/modallink',
        'modalmarkup': 'modalmarkup/js/modalmarkup',
        'modaldynamiccontent': 'modaldynamiccontent/js/modaldynamiccontent',
        'manualcountrylanguagedesignationselection': 'manualcountrylanguagedesignationselection/js/manualcountrylanguagedesignationselection',
        'audiovideo': 'audiovideo/js/audiovideo',
        'contactlist': 'contactlist/js/contactlist',
        'address': 'address/js/address',
        'contact': 'contact/js/contact',
        'peoplecontactform': 'peoplecontactform/js/peoplecontactform',
        'promotionala': 'promotionala/js/promotionala',
        'promotionalb': 'promotionalb/js/promotionalb',
        'promotionalc': 'promotionalc/js/promotionalc',
        'promotionald': 'promotionald/js/promotionald',
        'quickselectoroverlay': 'quickselectoroverlay/js/quickselectoroverlay',
        'disclaimer': 'disclaimer/js/disclaimer',
        'officelocation': 'officelocation/js/officelocation',
        'promotionale': 'promotionale/js/promotionale',
        'contact-form': 'contact-form/js/contact-form',
        'contact-tabs': 'contact-tabs/js/contact-tabs',
        'eventpagetitle': 'eventpagetitle/js/eventpagetitle',
        'searchinputs': 'searchinputs/js/searchinputs',
        'emptyplaceholder': 'emptyplaceholder/js/emptyplaceholder',
        'quickview': 'quickview/js/quickview',
        'listing': 'listing/js/listing',
        'quickviewevents': 'quickviewevents/js/quickviewevents',
        'quickviewinsights': 'quickviewinsights/js/quickviewinsights',
        'quickviewpeople': 'quickviewpeople/js/quickviewpeople',
        'eventtabs': 'eventtabs/js/eventtabs',
        'eventresources': 'eventresources/js/eventresources',
        'alumnilinks': 'alumnilinks/js/alumnilinks',
        'basicfilmstripcarousel': 'basicfilmstripcarousel/js/basicfilmstripcarousel',
        'navflyoutc': 'navflyoutc/js/navflyoutc',
        'navflyoutb': 'navflyoutb/js/navflyoutb',
        'articlecarousel': 'articlecarousel/js/articlecarousel',
        'c018-resultinglist': 'c018-resultinglist/js/c018-resultinglist',
        'resultinglist': 'resultinglist/js/resultinglist',
        'contactpromo': 'contactpromo/js/contactpromo',
        'imageoverlay': 'imageoverlay/js/imageoverlay',
        'socialtab': 'socialtab/js/socialtab',
        'campaignpagetitle': 'campaignpagetitle/js/campaignpagetitle',
        'mykpmgpromo': 'mykpmgpromo/js/mykpmgpromo',
        'mykpmgpromob': 'mykpmgpromob/js/mykpmgpromob',
        'facets': 'facets/js/facets',
        'resultslisting': 'resultslisting/js/resultslisting',
        'resultlisting': 'resultlisting/js/resultlisting',
        'searchresults': 'searchresults/js/searchresults',
        'rfpprocess': 'rfpprocess/js/rfpprocess',
        'socialdashboard': 'socialdashboard/js/socialdashboard',
        'socialwidgetbuild': 'socialwidgetbuild/js/socialwidgetbuild',
        'imagegalleryoverlay': 'imagegalleryoverlay/js/imagegalleryoverlay',
        'imagegallery': 'imagegallery/js/imagegallery',
        'peoplefilmstripa': 'peoplefilmstripa/js/peoplefilmstripa',
        'tombstonegallery': 'tombstonegallery/js/tombstonegallery',
        'enhanceddownload': 'enhanceddownload/js/enhanceddownload',
        'registrationpagetitle': 'registrationpagetitle/js/registrationpagetitle',
        'registrationuserinfo': 'registrationuserinfo/js/registrationuserinfo',
        'registrationinterests': 'registrationinterests/js/registrationinterests',

        'interestssummary': 'interestssummary/js/interestssummary',
        'profile': 'profile/js/profile',
        'mykpmgflyout': 'mykpmgflyout/js/mykpmgflyout',
        'loginform': 'loginform/js/loginform',
        'deleteaccountlink': 'deleteaccountlink/js/deleteaccountlink',
        'addtolibrary': 'addtolibrary/js/addtolibrary',
        'interests': 'interests/js/interests',
        'dashboardarticle': 'dashboardarticle/js/dashboardarticle',
        'widedashboardarticle': 'widedashboardarticle/js/widedashboardarticle',
        'librarysummary': 'librarysummary/js/librarysummary',
        'kpmglearnmore': 'kpmglearnmore/js/kpmglearnmore',
        'addtolibraryoverlay': 'addtolibraryoverlay/js/addtolibraryoverlay',
        'librarylistmanagement': 'librarylistmanagement/js/librarylistmanagement',
        'librarylist': 'librarylist/js/librarylist',
        'dashboardbanner': 'dashboardbanner/js/dashboardbanner',
        'sharedlist': 'sharedlist/js/sharedlist',
        'toppicks': 'toppicks/js/toppicks',
        'contentrefreshctas': 'contentrefreshctas/js/contentrefreshctas',
        'contentrefreshfeedback': 'contentrefreshfeedback/js/contentrefreshfeedback',
        'printbutton': 'printbutton/js/printbutton',
        'contactbutton': 'contactbutton/js/contactbutton',
        'partnerlocator': 'partnerlocator/js/partnerlocator',
        'officelocator': 'officelocator/js/officelocator',
        'fullbleedbanner': 'fullbleedbanner/js/fullbleedbanner',
        'ddtfullbleedbanner': 'ddtfullbleedbanner/js/ddtfullbleedbanner',
        'quote': 'quote/js/quote',
        'sidebartextandimage': 'sidebartextandimage/js/sidebartextandimage',
        'manualsubnav': 'manualsubnav/js/manualsubnav',
        'resultlistingb': 'resultlistingb/js/resultlistingb',
        'caasdocumentheader': 'caasdocumentheader/js/caasdocumentheader',
        'caasdocumentfooter': 'caasdocumentfooter/js/caasdocumentfooter',
        'caasdocumentnav': 'caasdocumentnav/js/caasdocumentnav',
        'caasdocumentsearchresults': 'caasdocumentsearchresults/js/caasdocumentsearchresults',
        'caasdocumentbodytext': 'caasdocumentbodytext/js/caasdocumentbodytext',
        'caasdocumentbreadcrumb': 'caasdocumentbreadcrumb/js/caasdocumentbreadcrumb',
        'grecaptcha': 'grecaptcha/js/grecaptcha',
        'common-utils': 'common-utils/js/common-utils',
        'subscription-preferences': 'subscription-preferences/js/subscription-preferences',
        'unsubscribe': 'unsubscribe/js/unsubscribe',
        'privacy-preferences': 'privacy-preferences/js/privacy-preferences',
        'communication-preferences': 'communication-preferences/js/communication-preferences',
        'email-header': 'email-header/js/email-header',
        'email-body': 'email-body/js/email-body',
        'email-footer': 'email-footer/js/email-footer',
        // end routes modules

        'navigation-v2'             : 'navigation-v2/js/navigation-v2',
        'quickselectoroverlay-v2'             : 'quickselectoroverlay-v2/js/quickselectoroverlay-v2',
        'my-account-flyout-2'             : 'my-account-flyout-2/js/my-account-flyout-2',
        'footer-v2'             : 'footer-v2/js/footer-v2',
        'oppmodal'             : 'oppmodal/js/oppmodal',
        'touch-trifectabanner'             : 'touch-trifectabanner/js/touch-trifectabanner',
        'touch-promotional'             : 'touch-promotional/js/touch-promotional',
        'touch-recentposts'             : 'touch-recentposts/js/touch-recentposts',
        'touch-featuredauthors'             : 'touch-featuredauthors/js/touch-featuredauthors',
        'touch-podcast'             : 'touch-podcast/js/touch-podcast',
        'touch-videobanner'             : 'touch-videobanner/js/touch-videobanner',
        'touch-supportingcontent'             : 'touch-supportingcontent/js/touch-supportingcontent',
        'touch-fullbleed'             : 'touch-fullbleed/js/touch-fullbleed',
        'touch-download'             : 'touch-download/js/touch-download',
        'touch-blog-footer'             : 'touch-blog-footer/js/touch-blog-footer',
        'touch-popularposts'             : 'touch-popularposts/js/touch-popularposts',
        'touch-populartags'             : 'touch-populartags/js/touch-populartags',
        'touch-postbody'             : 'touch-postbody/js/touch-postbody',
        'touch-relatedposts'             : 'touch-relatedposts/js/touch-relatedposts',
        'touch-bloglikes'             : 'touch-bloglikes/js/touch-bloglikes',
        'touch-blogshare'             : 'touch-blogshare/js/touch-blogshare',
        'touch-bloglikesandshare'             : 'touch-bloglikesandshare/js/touch-bloglikesandshare',
        'touch-post-highlight'             : 'touch-post-highlight/js/touch-post-highlight',
        'ddt-landing-utils': 'tmpl-ddt-landing/js/ddt-landing-utils',
        'touch-details'             : 'touch-details/js/touch-details',
        'touch-video-post'             : 'touch-video-post/js/touch-video-post',
        'blogs-comment'             : 'blogs-comment/js/blogs-comment',
        'touch-post-stats'             : 'touch-post-stats/js/touch-post-stats',
        'touch-bodytext'             : 'touch-bodytext/js/touch-bodytext',
        'touch-blog-author-list'             : 'touch-blog-author-list/js/touch-blog-author-list',
        'touch-blog-topic-list'             : 'touch-blog-topic-list/js/touch-blog-topic-list',
        'touch-author-spotlight'             : 'touch-author-spotlight/js/touch-author-spotlight',
        'touch-author-list-header'             : 'touch-author-list-header/js/touch-author-list-header',
        'touch-topic-list-header'             : 'touch-topic-list-header/js/touch-topic-list-header',
        'latest-thinking'            : 'latest-thinking/js/latest-thinking',
        'triocomponent'              : 'triocomponent/js/triocomponent',
        'overviewpanel'              : 'overviewpanel/js/overviewpanel',
        'globalleadership'           : 'globalleadership/js/globalleadership',
        'touch-image'             : 'touch-image/js/touch-image',
        'touch-inlinelist'             : 'touch-inlinelist/js/touch-inlinelist',
        'touch-columncontrol'             : 'touch-columncontrol/js/touch-columncontrol',
        'touch-breadcrumb'             : 'touch-breadcrumb/js/touch-breadcrumb',
        'touch-author-summary'             : 'touch-author-summary/js/touch-author-summary',
        'touch-mykpmgpromo'             : 'touch-mykpmgpromo/js/touch-mykpmgpromo',
        'login-done'             : 'login-done/js/login-done',
        'sticky-bar'             : 'sticky-bar/js/sticky-bar',
        'sticky-bar-service'             : 'sticky-bar/js/sticky-bar-service',
        'registration-promo'             : 'registration-promo/js/registration-promo',
        'registration-promo-overlay'             : 'registration-promo-overlay/js/registration-promo-overlay',
        'touch-language-toggle'         : 'touch-language-toggle/js/touch-language-toggle',
        'fge-cta'                       : 'fge-cta/js/fge-cta',
        'touch-language-toggle'         : 'touch-language-toggle/js/touch-language-toggle',

        'formbuilder'             : 'formbuilder/js/formbuilder',
        // end routes modules

        // VUE DIRECTIVES
        'vue-dev-directive': 'vue-directives/v-dev/js/v-dev',
        "v-process-url": "vue-directives/v-process-url/js/v-process-url",

        // VUEX STORE
        'vuex-store': 'vuex/store/js/store',
        // VUEX MODULES
        'vuex-data-module': 'vuex/modules/js/data/data',
        //
        'vuex-components-module': 'vuex/modules/js/components/components',
        'vuex-components-module-store': 'vuex/modules/js/components/mobile-navbar/store',
        'vuex-components-module-mutations': 'vuex/modules/js/components/mobile-navbar/mutations',

        // VUEX-NAVIGATION
        'vuex-navigation-module': 'vuex/modules/js/data/navigation/navigation',
        'vuex-navigation-state': 'vuex/modules/js/data/navigation/state',
        'vuex-navigation-actions': 'vuex/modules/js/data/navigation/actions',
        'vuex-navigation-mutations': 'vuex/modules/js/data/navigation/mutations',
        'vuex-navigation-getters': 'vuex/modules/js/data/navigation/getters',

        // VUEX SITE-INFO MODULE
        'vuex-site-info-module': 'vuex/modules/js/data/site-info',

        // VUEX-PERSONALIZATION
        'vuex-personalization-module': 'vuex/modules/js/data/vuex-personalization/vuex-personalization',
        'vuex-personalization-state': 'vuex/modules/js/data/vuex-personalization/state',
        'vuex-personalization-actions': 'vuex/modules/js/data/vuex-personalization/actions',
        'vuex-personalization-mutations': 'vuex/modules/js/data/vuex-personalization/mutations',

        // VUEX-SEARCH MODULE
        'vuex-search-module': 'vuex/modules/js/data/search',

        // settings:
        'config': 'global/js/config',
        'footersubscriptionrfp': 'footersubscriptionrfp/js/footersubscriptionrfp'
    }
});
